version: '3.1'

# It is recommended to replace the username and passwords
# If you wish to deploy this outside of a your computer or your secured local network, you should probably implement TLS

services:
  mongo:
    image: mongo
    restart: always
    volumes:
      - ./data/db/:/data/db
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: passAdminUser
      MONGO_INITDB_ROOT_PASSWORD: passManagerPass

  server:
    container_name: server
    build: ./server
    depends_on:
      - mongo
    restart: always
    environment:
      - SERVER_PORT=8080
      - MONGO_USERNAME=passAdminUser
      - MONGO_PASSWORD=passManagerPass
      - MONGO_ADDR=mongo
      - MONGO_PORT=27017
      - SECRET_KEY=my_secret_key # To replace
    ports:
      - "8080:8080"